### ISSUE TITLE
JavaScriptCore compiler error on OS X

### ISSUE THREAD

**Issue by IvayloDankolov** [ericwlange/hemroid#2]
Seems like webkitgtk is using <thread> and it's not getting compiled using std=c++11 . Where would be the best place to pass that flag to GCC?

[Here's](https://gist.github.com/IvayloDankolov/6246197b457f8ba8d9f58983321a3903) the hemroid log.

**Comment by ericwlange** [comment]
What version of the NDK are you using?  I haven't seen this problem.  I have compiled JavaScriptCore at least 30,000 times on both OSX and Linux.  I am using r10e.

**Comment by IvayloDankolov** [comment]
Seems to be an NDK bug. Android Studio apparently downloaded 12 beta without listing it as beta... I'll test on r11c.

**Comment by ericwlange** [comment]
Did switching back NDKs solve this issue?

**Comment by ericwlange** [comment]
This is now updated for NDK 12
